### ISSUE TITLE
Deliver a Favicon

### ISSUE THREAD

**Issue by nicokaiser** [juliangruber/traffic-light#1]
Currently, the service delivers a traffic light PNG also for /favicon.ico which leads to a distorted red light in the browser tabs.

The webservice should check if a valid URL is appended and if not, throw an error (and of course listen for /favicon.ico).

**Comment by juliangruber** [comment]
done and published, see 8ba5834bf0cfae4961ced4eeabc6a26ecfdf2f20

A PR for a nicer favicon would be appreciated :)
